# Generated by Django 3.2.8 on 2022-08-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211117_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mode',
            field=models.CharField(default='simple', max_length=255),
        ),
    ]
