# Generated by Django 4.2.29 on 2026-03-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
